<a href="https://colab.research.google.com/github/kostismatz/GKS_ML_Project/blob/main/2BiRNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.cuda.is_available())
import torch
print(torch.__version__)



# -*- coding: utf-8 -*-
"""

A RNN classifier applied to AG_NEWS dataset

Download dataset:
https://www.kaggle.com/datasets/amananandrai/ag-news-classification-dataset

"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import time
from torch.utils.data import DataLoader
from torch import nn
from torch.nn import functional as F
import pandas as pd
from tqdm import tqdm
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from collections import Counter

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

MAX_WORDS = 25
EPOCHS = 15
LEARNING_RATE = 1e-3
BATCH_SIZE = 1024
EMBEDDING_DIM = 100
HIDDEN_DIM = 64

train_data = pd.read_csv('train.csv')
test_data = pd.read_csv('test.csv')

######################################################################
# Data processing
# -----------------------------


def tokenizer(text):
    return text.lower().split()

# All texts are truncated and padded to MAX_WORDS tokens
def collate_batch(batch):
    Y, X = zip(*batch)

    Y = torch.tensor(Y, dtype=torch.long) - 1

    X_processed = []

    for text in X:
        tokens = tokenizer(text)

        indices = []
        for token in tokens:
            if token in vocab:
                indices.append(vocab[token])
            else:
                indices.append(vocab["<UNK>"])

        if len(indices) < MAX_WORDS:
            indices += [vocab["<PAD>"]] * (MAX_WORDS - len(indices))
        else:
            indices = indices[:MAX_WORDS]

        X_processed.append(indices)

    X_tensor = torch.tensor(X_processed, dtype=torch.long)

    return X_tensor.to(device), Y.to(device)

train_dataset = [(label,train_data['Title'][i] + ' ' + train_data['Description'][i]) for i,label in enumerate(train_data['Class Index'])]
test_dataset = [(label,test_data['Title'][i] + ' ' + test_data['Description'][i]) for i,label in enumerate(test_data['Class Index'])]

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE,
                              shuffle=True, collate_fn=collate_batch)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE,
                              shuffle=False, collate_fn=collate_batch)

target_classes = ["World", "Sports", "Business", "Sci/Tech"]

def build_vocabulary(dataset, min_freq=10):
    counter = Counter()

    for _, text in dataset:
        tokens = tokenizer(text)
        counter.update(tokens)

    vocab_dict = {
        "<PAD>": 0,
        "<UNK>": 1
    }

    idx = 2
    for token, freq in counter.items():
        if freq >= min_freq:
            vocab_dict[token] = idx
            idx += 1

    return vocab_dict

vocab = build_vocabulary(train_dataset, min_freq=10)


class model(nn.Module):
    def __init__(self, input_dim, embedding_dim, hidden_dim, output_dim):
        super(model, self).__init__()

        self.rnn = nn.RNN(
            input_size=embedding_dim,
            hidden_size=hidden_dim,
            num_layers=2,
            batch_first=True,
            bidirectional=True
        )

        self.embedding_layer = nn.Embedding(input_dim, embedding_dim)

        self.linear = nn.Linear(hidden_dim * 2, output_dim)

    def forward(self, X_batch):
        embeddings = self.embedding_layer(X_batch)

        output, hidden = self.rnn(embeddings)

        # 🔥 σωστό BiRNN pooling
        out = torch.cat((hidden[-2], hidden[-1]), dim=1)

        return self.linear(out)


 # Initiate an instance of the model
# ---------------------------------


classifier = model(len(vocab), EMBEDDING_DIM, HIDDEN_DIM, len(target_classes)).to(device)
# Define loss function and opimization algorithm
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam([param for param in classifier.parameters() if param.requires_grad == True],lr=LEARNING_RATE)

# Count model parameters
def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

print('\nModel:')
print(classifier)
print('Total parameters: ',count_parameters(classifier))
print('\n\n')

######################################################################



# Define functions to train and evaluate the model
# ------------------------------------------------


def EvaluateModel(model, loss_fn, val_loader):
    model.eval()
    with torch.no_grad():

        Y_actual, Y_preds, losses = [], [], []

        for X, Y in val_loader:

            # 🔥 MOVE TO GPU
            X = X.to(device)
            Y = Y.to(device)

            preds = model(X)
            loss = loss_fn(preds, Y)

            losses.append(loss.item())

            Y_actual.append(Y)
            Y_preds.append(preds.argmax(dim=-1))

        Y_actual = torch.cat(Y_actual)
        Y_preds = torch.cat(Y_preds)

    return torch.tensor(losses).mean(), Y_actual.cpu().numpy(), Y_preds.cpu().numpy()


def TrainModel(model, loss_fn, optimizer, train_loader, epochs):
    epoch_times = []

    for i in range(1, epochs+1):
        model.train()
        print('Epoch:', i)

        losses = []

        start_time = time.time()

        for X, Y in tqdm(train_loader):

            # 🔥 MOVE TO GPU
            X = X.to(device)
            Y = Y.to(device)

            Y_preds = model(X)
            loss = loss_fn(Y_preds, Y)

            losses.append(loss.item())

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

        end_time = time.time()

        epoch_time = end_time - start_time
        epoch_times.append(epoch_time)

        print("Train Loss : {:.3f}".format(torch.tensor(losses).mean()))
        print("Epoch Time (sec): {:.2f}".format(epoch_time))

    print("\nAverage Epoch Time:", sum(epoch_times)/len(epoch_times))

import os
os.environ["CUDA_LAUNCH_BLOCKING"] = "1"

TrainModel(classifier, loss_fn, optimizer, train_loader, EPOCHS)


# Evaluate the model with test dataset
# ------------------------------------


_, Y_actual, Y_preds = EvaluateModel(classifier, loss_fn, test_loader)

print("\nTest Accuracy : {:.3f}".format(accuracy_score(Y_actual, Y_preds)))
print("\nClassification Report : ")
print(classification_report(Y_actual, Y_preds, target_names=target_classes))
print("\nConfusion Matrix : ")
print(confusion_matrix(Y_actual, Y_preds))


# =========================
# 🔁 3 RUN EXPERIMENT
# =========================

from sklearn.metrics import accuracy_score
import numpy as np

accuracies = []

for run in range(3):
    print(f"\n===== RUN {run+1} =====")

    # νέο model κάθε φορά
    classifier = model(len(vocab), EMBEDDING_DIM, HIDDEN_DIM, len(target_classes)).to(device)

    optimizer = torch.optim.Adam(classifier.parameters(), lr=LEARNING_RATE)

    # training
    TrainModel(classifier, loss_fn, optimizer, train_loader, EPOCHS)

    # evaluation
    _, y_true, y_pred = EvaluateModel(classifier, loss_fn, test_loader)

    acc = accuracy_score(y_true, y_pred)
    accuracies.append(acc)

    print("Test Accuracy:", acc)


    print("\n===== FINAL RESULTS =====")

mean_acc = np.mean(accuracies)
std_acc = np.std(accuracies)

print("Accuracies:", accuracies)
print("Mean Accuracy:", mean_acc)
print("Std:", std_acc)





True
2.10.0+cu128
cuda

Model:
model(
  (rnn): RNN(100, 64, num_layers=2, batch_first=True, bidirectional=True)
  (embedding_layer): Embedding(25099, 100)
  (linear): Linear(in_features=128, out_features=4, bias=True)
)
Total parameters:  2556496



Epoch: 1


100%|██████████| 118/118 [00:03<00:00, 35.38it/s]


Train Loss : 1.033
Epoch Time (sec): 3.34
Epoch: 2


100%|██████████| 118/118 [00:02<00:00, 47.86it/s]


Train Loss : 0.564
Epoch Time (sec): 2.47
Epoch: 3


100%|██████████| 118/118 [00:02<00:00, 52.45it/s]


Train Loss : 0.416
Epoch Time (sec): 2.25
Epoch: 4


100%|██████████| 118/118 [00:02<00:00, 56.62it/s]


Train Loss : 0.340
Epoch Time (sec): 2.09
Epoch: 5


100%|██████████| 118/118 [00:02<00:00, 54.90it/s]


Train Loss : 0.291
Epoch Time (sec): 2.15
Epoch: 6


100%|██████████| 118/118 [00:02<00:00, 52.72it/s]


Train Loss : 0.255
Epoch Time (sec): 2.24
Epoch: 7


100%|██████████| 118/118 [00:02<00:00, 40.11it/s]


Train Loss : 0.226
Epoch Time (sec): 2.95
Epoch: 8


100%|██████████| 118/118 [00:02<00:00, 49.54it/s]


Train Loss : 0.200
Epoch Time (sec): 2.39
Epoch: 9


100%|██████████| 118/118 [00:02<00:00, 55.36it/s]


Train Loss : 0.179
Epoch Time (sec): 2.14
Epoch: 10


100%|██████████| 118/118 [00:02<00:00, 55.41it/s]


Train Loss : 0.157
Epoch Time (sec): 2.13
Epoch: 11


100%|██████████| 118/118 [00:02<00:00, 57.05it/s]


Train Loss : 0.141
Epoch Time (sec): 2.07
Epoch: 12


100%|██████████| 118/118 [00:03<00:00, 38.74it/s]


Train Loss : 0.124
Epoch Time (sec): 3.05
Epoch: 13


100%|██████████| 118/118 [00:02<00:00, 56.23it/s]


Train Loss : 0.107
Epoch Time (sec): 2.10
Epoch: 14


100%|██████████| 118/118 [00:02<00:00, 57.01it/s]


Train Loss : 0.094
Epoch Time (sec): 2.07
Epoch: 15


100%|██████████| 118/118 [00:02<00:00, 51.44it/s]


Train Loss : 0.082
Epoch Time (sec): 2.30

Average Epoch Time: 2.3825763861338296

Test Accuracy : 0.876

Classification Report : 
              precision    recall  f1-score   support

       World       0.84      0.93      0.88      1900
      Sports       0.96      0.92      0.94      1900
    Business       0.87      0.80      0.83      1900
    Sci/Tech       0.84      0.86      0.85      1900

    accuracy                           0.88      7600
   macro avg       0.88      0.88      0.88      7600
weighted avg       0.88      0.88      0.88      7600


Confusion Matrix : 
[[1760   35   55   50]
 [  91 1742   34   33]
 [ 138   21 1522  219]
 [ 102   20  141 1637]]

===== RUN 1 =====
Epoch: 1


100%|██████████| 118/118 [00:02<00:00, 58.56it/s]


Train Loss : 1.050
Epoch Time (sec): 2.02
Epoch: 2


100%|██████████| 118/118 [00:02<00:00, 48.36it/s]


Train Loss : 0.571
Epoch Time (sec): 2.44
Epoch: 3


100%|██████████| 118/118 [00:02<00:00, 46.52it/s]


Train Loss : 0.417
Epoch Time (sec): 2.54
Epoch: 4


100%|██████████| 118/118 [00:02<00:00, 58.69it/s]


Train Loss : 0.341
Epoch Time (sec): 2.01
Epoch: 5


100%|██████████| 118/118 [00:02<00:00, 53.71it/s]


Train Loss : 0.293
Epoch Time (sec): 2.20
Epoch: 6


100%|██████████| 118/118 [00:02<00:00, 57.89it/s]


Train Loss : 0.257
Epoch Time (sec): 2.04
Epoch: 7


100%|██████████| 118/118 [00:02<00:00, 55.38it/s]


Train Loss : 0.227
Epoch Time (sec): 2.13
Epoch: 8


100%|██████████| 118/118 [00:02<00:00, 40.62it/s]


Train Loss : 0.204
Epoch Time (sec): 2.91
Epoch: 9


100%|██████████| 118/118 [00:02<00:00, 57.85it/s]


Train Loss : 0.179
Epoch Time (sec): 2.04
Epoch: 10


100%|██████████| 118/118 [00:02<00:00, 58.64it/s]


Train Loss : 0.160
Epoch Time (sec): 2.02
Epoch: 11


100%|██████████| 118/118 [00:02<00:00, 57.84it/s]


Train Loss : 0.141
Epoch Time (sec): 2.04
Epoch: 12


100%|██████████| 118/118 [00:02<00:00, 54.54it/s]


Train Loss : 0.124
Epoch Time (sec): 2.17
Epoch: 13


100%|██████████| 118/118 [00:02<00:00, 51.22it/s]


Train Loss : 0.113
Epoch Time (sec): 2.31
Epoch: 14


100%|██████████| 118/118 [00:02<00:00, 44.70it/s]


Train Loss : 0.099
Epoch Time (sec): 2.64
Epoch: 15


100%|██████████| 118/118 [00:02<00:00, 58.39it/s]


Train Loss : 0.086
Epoch Time (sec): 2.03

Average Epoch Time: 2.236773729324341
Test Accuracy: 0.8759210526315789

===== FINAL RESULTS =====

===== RUN 2 =====
Epoch: 1


100%|██████████| 118/118 [00:02<00:00, 58.17it/s]


Train Loss : 1.049
Epoch Time (sec): 2.03
Epoch: 2


100%|██████████| 118/118 [00:02<00:00, 55.20it/s]


Train Loss : 0.577
Epoch Time (sec): 2.14
Epoch: 3


100%|██████████| 118/118 [00:01<00:00, 59.73it/s]


Train Loss : 0.415
Epoch Time (sec): 1.98
Epoch: 4


100%|██████████| 118/118 [00:02<00:00, 40.84it/s]


Train Loss : 0.338
Epoch Time (sec): 2.89
Epoch: 5


100%|██████████| 118/118 [00:02<00:00, 56.88it/s]


Train Loss : 0.291
Epoch Time (sec): 2.08
Epoch: 6


100%|██████████| 118/118 [00:01<00:00, 59.06it/s]


Train Loss : 0.254
Epoch Time (sec): 2.00
Epoch: 7


100%|██████████| 118/118 [00:01<00:00, 59.20it/s]


Train Loss : 0.225
Epoch Time (sec): 2.00
Epoch: 8


100%|██████████| 118/118 [00:01<00:00, 59.50it/s]


Train Loss : 0.199
Epoch Time (sec): 1.99
Epoch: 9


100%|██████████| 118/118 [00:02<00:00, 50.44it/s]


Train Loss : 0.180
Epoch Time (sec): 2.34
Epoch: 10


100%|██████████| 118/118 [00:02<00:00, 42.02it/s]


Train Loss : 0.160
Epoch Time (sec): 2.81
Epoch: 11


100%|██████████| 118/118 [00:01<00:00, 59.47it/s]


Train Loss : 0.140
Epoch Time (sec): 1.99
Epoch: 12


100%|██████████| 118/118 [00:01<00:00, 60.65it/s]


Train Loss : 0.127
Epoch Time (sec): 1.95
Epoch: 13


100%|██████████| 118/118 [00:01<00:00, 60.03it/s]


Train Loss : 0.113
Epoch Time (sec): 1.97
Epoch: 14


100%|██████████| 118/118 [00:02<00:00, 53.20it/s]


Train Loss : 0.099
Epoch Time (sec): 2.22
Epoch: 15


100%|██████████| 118/118 [00:02<00:00, 45.21it/s]


Train Loss : 0.085
Epoch Time (sec): 2.61

Average Epoch Time: 2.2006742636362713
Test Accuracy: 0.8786842105263157

===== FINAL RESULTS =====

===== RUN 3 =====
Epoch: 1


100%|██████████| 118/118 [00:02<00:00, 51.45it/s]


Train Loss : 1.050
Epoch Time (sec): 2.30
Epoch: 2


100%|██████████| 118/118 [00:01<00:00, 59.69it/s]


Train Loss : 0.559
Epoch Time (sec): 1.98
Epoch: 3


100%|██████████| 118/118 [00:02<00:00, 58.50it/s]


Train Loss : 0.410
Epoch Time (sec): 2.02
Epoch: 4


100%|██████████| 118/118 [00:02<00:00, 58.22it/s]


Train Loss : 0.338
Epoch Time (sec): 2.03
Epoch: 5


100%|██████████| 118/118 [00:02<00:00, 58.26it/s]


Train Loss : 0.290
Epoch Time (sec): 2.03
Epoch: 6


100%|██████████| 118/118 [00:03<00:00, 38.78it/s]


Train Loss : 0.256
Epoch Time (sec): 3.05
Epoch: 7


100%|██████████| 118/118 [00:02<00:00, 58.50it/s]


Train Loss : 0.228
Epoch Time (sec): 2.02
Epoch: 8


100%|██████████| 118/118 [00:02<00:00, 58.45it/s]


Train Loss : 0.200
Epoch Time (sec): 2.02
Epoch: 9


100%|██████████| 118/118 [00:01<00:00, 59.22it/s]


Train Loss : 0.178
Epoch Time (sec): 2.00
Epoch: 10


100%|██████████| 118/118 [00:01<00:00, 59.09it/s]


Train Loss : 0.156
Epoch Time (sec): 2.00
Epoch: 11


100%|██████████| 118/118 [00:02<00:00, 47.12it/s]


Train Loss : 0.142
Epoch Time (sec): 2.51
Epoch: 12


100%|██████████| 118/118 [00:02<00:00, 45.59it/s]


Train Loss : 0.123
Epoch Time (sec): 2.59
Epoch: 13


100%|██████████| 118/118 [00:02<00:00, 58.64it/s]


Train Loss : 0.111
Epoch Time (sec): 2.02
Epoch: 14


100%|██████████| 118/118 [00:01<00:00, 59.48it/s]


Train Loss : 0.094
Epoch Time (sec): 1.99
Epoch: 15


100%|██████████| 118/118 [00:01<00:00, 59.53it/s]


Train Loss : 0.081
Epoch Time (sec): 1.99

Average Epoch Time: 2.169016981124878
Test Accuracy: 0.883421052631579

===== FINAL RESULTS =====
Accuracies: [0.8759210526315789, 0.8786842105263157, 0.883421052631579]
Mean Accuracy: 0.8793421052631579
Std: 0.00309700060419472


# New Section